In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv(r'data_set_limpio/games_preparado.csv.gz')
item = pd.read_csv(r'data_set_limpio/items_preparado.csv.gz')
opinion = pd.read_csv(r'data_set_limpio/reviews_preparado.csv.gz')

In [37]:
def extraer_anio(fecha):
    if '-' in fecha:  # Si el formato es 'YYYY-MM-DD'
        return fecha.split('-')[0]
    else:  # Si el formato es 'MMM YYYY'
        partes = fecha.split(' ')
        if len(partes) == 2:
            return partes[1]
    return fecha

In [38]:
prueba1 = pd.merge(opinion[['item_id','opinion','user','recommend']], df[['release_date','id','developer']], left_on='item_id', right_on='id')

prueba1['recommend'] = prueba1['recommend'].replace({True: 1, False: 0})

prueba1['release_date'] = prueba1['release_date'].apply(extraer_anio)

for index, row in prueba1.iterrows():
    if row[1] == 2 and row[3] == 1:
        prueba1.at[index, 'Positivo'] = 1
    else:
        prueba1.at[index, 'Positivo'] = 0

prueba1['Positivo'] = prueba1['Positivo'].astype(int)

prueba1

C:\Users\jonat\AppData\Local\Temp\ipykernel_15608\1190263193.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[1] == 2 and row[3] == 1:
C:\Users\jonat\AppData\Local\Temp\ipykernel_15608\1190263193.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[1] == 2 and row[3] == 1:

,item_id,opinion,user,recommend,release_date,id,developer,Positivo
0,1250,1,76561197970982479,1,2009,1250,Tripwire Interactive,0
1,1250,1,death-hunter,1,2009,1250,Tripwire Interactive,0
2,1250,1,DJKamBer,1,2009,1250,Tripwire Interactive,0
3,1250,1,diego9031,1,2009,1250,Tripwire Interactive,0
4,1250,1,76561198081962345,1,2009,1250,Tripwire Interactive,0
...,...,...,...,...,...,...,...,...
49590,307130,1,llDracuwulf,1,2014,307130,Legend Studio,0
49591,209120,1,ChrisCoroner,1,2012,209120,"Capcom U.S.A., Inc.",0
49592,220090,1,MeloncraftLP,1,2013,220090,SkyGoblin,0
49593,262850,1,MeloncraftLP,1,2014,262850,SkyGoblin,0
49594,431510,1,vinquility,1,2016,431510,Aeon Dream Studios,0

In [39]:
anio = prueba1['release_date'].unique()

In [40]:
anio

array(['2009', '2013', '2015', '2014', '2011', '2016', '2012', '2004',
       '2007', '2017', '2006', '2010', '2002', '1995', '2003', '2005',
       '1998', '2008', '1990', '1992', '1993', '1999', '2000', '2001',
       '1997', '1996', '1994', '1989', '1991'], dtype=object)

In [41]:
end4 = {}
for x in anio:
    end4[x] = dict(prueba1.loc[(prueba1['release_date'] == x) & (prueba1['Positivo'] == 1)]['developer'].value_counts())

In [42]:
# Supongamos que este es tu diccionario original

# Creamos un nuevo diccionario para almacenar los resultados
filtered_dict = {}

# Iteramos sobre cada clave y valor en el diccionario original
for key, value in end4.items():
    filtered_dict[key] = dict(list(value.items())[:3])

filtered_dict

{'2009': {'Valve': 175,
  'Tripwire Interactive': 74,
  'Invent4 Entertainment': 14},
 '2013': {'Facepunch Studios': 117,
  'Digital Extremes': 115,
  'Bohemia Interactive': 107},
 '2015': {'Psyonix, Inc.': 60, 'Rockstar North': 44, 'Splash Damage': 27},
 '2014': {'Edge of Reality': 85,
  'Coffee Stain Studios': 48,
  'The Behemoth': 27},
 '2011': {'Re-Logic': 185, 'Valve': 71, 'No More Room in Hell Team': 55},
 '2016': {'Chucklefish': 45, 'Reto-Moto': 30, 'Tripwire Interactive': 18},
 '2012': {'Valve': 955,
  'Gearbox Software,Aspyr (Mac &amp; Linux)': 136,
  'Daybreak Game Company': 79},
 '2004': {'Valve': 100, 'The Creative Assembly': 5, 'Gray Matter Studios': 2},
 '2007': {'Valve': 1095, '2K Boston,2K Australia': 8, 'Zombie Panic Team': 8},
 '2017': {'Smartly Dressed Games': 189,
  'Freejam': 57,
  'Studio Wildcard,Instinct Games,Efecto Studios,Virtual Basement LLC': 32},
 '2006': {'Facepunch Studios': 392,
  'Nabi Studios': 15,
  'Relic Entertainment': 10},
 '2010': {'Firaxis Games,Aspyr (Mac, Linux)': 63,
  'TaleWorlds Entertainment': 43,
  'Obsidian Entertainment': 38},
 '2002': {'Bethesda Game Studios': 2, 'Rockstar Games': 1},
 '1995': {'LucasArts': 1},
 '2003': {'BioWare,Aspyr (Mac)': 2,
  'Raven Software,Aspyr (Mac)': 1,
  'Running With Scissors': 1},
 '2005': {'Pandemic Studios': 11, 'Synergy Team': 9, 'Rockstar Games': 5},
 '1998': {'Valve': 10, 'Black Isle Studios': 1, 'Oddworld Inhabitants': 1},
 '2008': {'Treyarch': 12, 'Valve': 7, 'Dylan Fitterer': 6},
 '1990': {'id Software': 1},
 '1992': {'Redwood Games': 1},
 '1993': {'MicroProse Software, Inc': 1},
 '1999': {'Valve': 3,
  'Sven Co-op Team': 3,
  'Irrational Games,Looking Glass Studios': 1},
 '2000': {'Valve': 13},
 '2001': {'Gearbox Software': 1, 'Red Storm Entertainment': 1},
 '1997': {'Oddworld Inhabitants': 3,
  'Running With Scissors': 1,
  'Cavedog Entertainment': 1},
 '1996': {},
 '1994': {},
 '1989': {},
 '1991': {}}

In [45]:
top1 = []
top2 = []
top3 = []

for x in anio:
    names = list(filtered_dict[x].keys())
    if len(names) >= 1:
        top1.append((names[0], filtered_dict[x][names[0]]))
    if len(names) >= 2:
        top2.append((names[1], filtered_dict[x][names[1]]))
    if len(names) >= 3:
        top3.append((names[2], filtered_dict[x][names[2]]))

In [46]:
import pandas as pd

# AsegÃºrate de que todas las listas tengan la misma longitud
max_len = max(len(anio), len(top1), len(top2), len(top3))
anio = list(anio)
top1 = list(top1)
top2 = list(top2)
top3 = list(top3)

# Rellena las listas con None si es necesario
anio.extend([''] * (max_len - len(anio)))
top1.extend([''] * (max_len - len(top1)))
top2.extend([''] * (max_len - len(top2)))
top3.extend([''] * (max_len - len(top3)))

# Crea el DataFrame
impo2 = pd.DataFrame(data={'Anio': anio, 'Top 1': top1, 'Top 2': top2, 'Top 3': top3})

In [52]:
impo2.to_csv('data_set_limpio\Max_developer_year.csv', index=False)